---
# create a namespac
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
# deploy a pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chessnet-deployment
  namespace: development
  labels:
    app: chessnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chessnet
  template:
    metadata:
      labels:
        app: chessnet
    spec:
      containers:
      - name: chessnet-container
        image: chessnet-server:latest-1
        ports:
        - containerPort: 3000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
--- 
# deploy a loadbalancer (service)
apiVersion: v1
kind: Service
metadata:
  name: chessnet-loadbalancer
  namespace: development
spec:
  selector:
    app: chessnet-server
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
