---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chessnet-deployment
  namespace: chessnet-namespace
  labels:
    app: chessnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chessnet
  template:
    metadata:
      name: chessnet-pod
      labels:
        app: chessnet
    spec:
      containers:
      - name: chessnet-container
        image: chessnet-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
